require("rand")
require("schema")

-- cache global to local
local _gen_default_value_f = _gen_default_value
local _gen_default_parameter_f = _gen_default_parameter
local _tables_t = tables

function get_table_size(_table_name)
    return _default_tables_size[_table_name]
end

function gen_value(_table_name, _col_name, _col_desc, _line_num)
    return _gen_default_value_f(_table_name, _col_name, _col_desc, _line_num)
end

function gen_parameter(_param_desc)
    local _api = _param_desc[1]
    local _sql = _param_desc[2]
    local _table = _param_desc[3]
    local _column = _param_desc[4]
    local _position = _param_desc[5]
    local _guessed_data_type = _param_desc[6]

    local _column_desc
    if _table ~= "" then
        _column_desc = _tables_t[_table][_column]
    end

    return _gen_default_parameter_f(_table, _column, _column_desc, _position, _guessed_data_type)
end
_default_tables_size = {
  ["s_menu"] = 10000,
  ["s_position"] = 10000,
  ["s_menu_group"] = 10000,
  ["s_autz_detail"] = 10000,
  ["qrtz_cron_triggers"] = 10000,
  ["act_re_deployment"] = 10000,
  ["act_ge_property"] = 10000,
  ["act_ru_event_subscr"] = 10000,
  ["s_relation_def"] = 10000,
  ["act_id_membership"] = 10000,
  ["act_ru_identitylink"] = 10000,
  ["s_dashboard_conf"] = 10000,
  ["qrtz_blob_triggers"] = 10000,
  ["qrtz_triggers"] = 10000,
  ["s_wf_proc_his"] = 10000,
  ["s_wf_act_conf"] = 10000,
  ["act_hi_taskinst"] = 10000,
  ["s_department"] = 10000,
  ["s_user_role"] = 10000,
  ["s_user_setting"] = 10000,
  ["qrtz_simple_triggers"] = 10000,
  ["s_relation_info"] = 10000,
  ["s_dict_parser"] = 10000,
  ["s_dyn_form_column"] = 10000,
  ["act_hi_actinst"] = 10000,
  ["act_hi_identitylink"] = 10000,
  ["act_ru_execution"] = 10000,
  ["s_menu_group_bind"] = 10000,
  ["act_ge_bytearray"] = 10000,
  ["s_dictionary"] = 10000,
  ["qrtz_locks"] = 10000,
  ["s_user"] = 10000,
  ["act_id_info"] = 10000,
  ["s_autz_menu"] = 10000,
  ["s_oauth2_server"] = 10000,
  ["act_hi_comment"] = 10000,
  ["s_person_position"] = 10000,
  ["s_district"] = 10000,
  ["s_file_info"] = 10000,
  ["s_system"] = 10000,
  ["s_permission"] = 10000,
  ["s_dict_item"] = 10000,
  ["act_ru_variable"] = 10000,
  ["s_wf_proc_conf"] = 10000,
  ["s_permission_role"] = 10000,
  ["act_re_procdef"] = 10000,
  ["act_hi_procinst"] = 10000,
  ["s_oauth2_client"] = 10000,
  ["s_datasource_conf"] = 10000,
  ["act_hi_attachment"] = 10000,
  ["act_evt_log"] = 10000,
  ["act_hi_varinst"] = 10000,
  ["qrtz_scheduler_state"] = 10000,
  ["s_person"] = 10000,
  ["s_template"] = 10000,
  ["s_dyn_form"] = 10000,
  ["act_id_group"] = 10000,
  ["act_hi_detail"] = 10000,
  ["qrtz_calendars"] = 10000,
  ["act_id_user"] = 10000,
  ["act_ru_job"] = 10000,
  ["act_procdef_info"] = 10000,
  ["s_dyn_form_log"] = 10000,
  ["act_ru_task"] = 10000,
  ["s_schedule_job"] = 10000,
  ["s_script"] = 10000,
  ["qrtz_paused_trigger_grps"] = 10000,
  ["s_role"] = 10000,
  ["act_re_model"] = 10000,
  ["qrtz_job_details"] = 10000,
  ["s_oauth2_access"] = 10000,
  ["qrtz_fired_triggers"] = 10000,
  ["s_oauth2_user_token"] = 10000,
  ["s_organization"] = 10000,
  ["qrtz_simprop_triggers"] = 10000,
  ["s_autz_setting"] = 10000,
  ["s_oauth2_auth_code"] = 10000,
}

_traces_dist = {
  { "API_1_GET_menu_user_own_tree_1", -1 },
  { "API_1_GET_menu_user_own_tree_2", -1 },
  { "API_2_POST_schedule_job_excxcxfxfxfxaxex_execute_1", -1 },
  { "API_3_GET_template_1", -1 },
  { "API_3_GET_template_2", -1 },
  { "API_3_GET_template_3", -1 },
  { "API_4_GET_autz_setting_user_dxdxexexacxcxcfxdxex_1", -1 },
  { "API_5_DELETE_menu_xdxacecxaxeaxbxdxexcx_1", -1 },
  { "API_6_PUT_user_xdxdaxecxaecxaxeaxf_1", -1 },
  { "API_7_PATCH_schedule_job_1", -1 },
  { "API_8_PATCH_template_1", -1 },
  { "API_8_PATCH_template_2", -1 },
  { "API_9_PATCH_permission_1", -1 },
  { "API_10_PUT_user_lock_lock_1", -1 },
  { "API_11_PATCH_user_setting_me_code_gen_setsimple_gen_1", -1 },
  { "API_11_PATCH_user_setting_me_code_gen_setsimple_gen_2", -1 },
  { "API_12_GET_autz_setting_detail_permission_x_1", -1 },
  { "API_13_GET_role_1", -1 },
  { "API_13_GET_role_2", -1 },
  { "API_13_GET_role_3", -1 },
  { "API_13_GET_role_4", -1 },
  { "API_13_GET_role_5", -1 },
  { "API_14_GET_autz_setting_role_dd_1", -1 },
  { "API_15_GET_menu_xdxacecxaxeaxbxdxexcx_1", -1 },
  { "API_16_GET_organizational_1", -1 },
  { "API_16_GET_organizational_2", -1 },
  { "API_17_POST_permission_1", -1 },
  { "API_17_POST_permission_2", -1 },
  { "API_18_PUT_role_dd_1", -1 },
  { "API_19_GET_autz_setting_detail_oauthx_client_config_1", -1 },
  { "API_20_PUT_schedule_job_undefined_enable_1", -1 },
  { "API_21_GET_menu_1", -1 },
  { "API_21_GET_menu_2", -1 },
  { "API_21_GET_menu_3", -1 },
  { "API_21_GET_menu_4", -1 },
  { "API_22_GET_permission_organizational_1", -1 },
  { "API_22_GET_permission_organizational_2", -1 },
  { "API_23_POST_workflow_model__1", -1 },
  { "API_23_POST_workflow_model__2", -1 },
  { "API_24_PUT_workflow_model_x_1", -1 },
  { "API_25_PATCH_dictionary_item_batch_1", -1 },
  { "API_26_PUT_workflow_model_x_1", -1 },
  { "API_27_PUT_user_lock_lock_password_1", -1 },
  { "API_28_GET_organizational_no_paging_1", -1 },
  { "API_29_GET_permission_permission_x_1", -1 },
  { "API_30_DELETE_autz_setting_undefined_organizational_1", -1 },
  { "API_30_DELETE_autz_setting_undefined_organizational_2", -1 },
  { "API_31_GET_dictionary_item_no_paging_1", -1 },
  { "API_32_GET_workflow_model_x_json_1", -1 },
  { "API_33_PUT_schedule_job_undefined_disable_1", -1 },
  { "API_34_POST_authorize_login_1", -1 },
  { "API_34_POST_authorize_login_2", -1 },
  { "API_34_POST_authorize_login_3", -1 },
  { "API_35_GET_user_xdxdaxecxaecxaxeaxf_1", -1 },
  { "API_36_PATCH_dictionary_item__1", -1 },
  { "API_37_GET_dictionary_1", -1 },
  { "API_37_GET_dictionary_2", -1 },
  { "API_37_GET_dictionary_3", -1 },
  { "API_37_GET_dictionary_4", -1 },
  { "API_38_PATCH_datasource_config_1", -1 },
  { "API_38_PATCH_datasource_config_2", -1 },
  { "API_39_DELETE_workflow_model_x_1", -1 },
  { "API_40_PATCH_dynamic_form_bind_1", -1 },
  { "API_40_PATCH_dynamic_form_bind_2", -1 },
  { "API_41_PUT_autz_setting_merge_1", -1 },
  { "API_41_PUT_autz_setting_merge_2", -1 },
  { "API_41_PUT_autz_setting_merge_3", -1 },
  { "API_41_PUT_autz_setting_merge_4", -1 },
  { "API_41_PUT_autz_setting_merge_5", -1 },
  { "API_41_PUT_autz_setting_merge_6", -1 },
  { "API_42_DELETE_permission_permission_x_1", -1 },
  { "API_43_GET_permission_oauthx_client_config_1", -1 },
  { "API_44_GET_datasource_1", -1 },
  { "API_45_GET_user_1", -1 },
  { "API_45_GET_user_2", -1 },
  { "API_45_GET_user_3", -1 },
  { "API_46_DELETE_dictionary_item_efxbabefxaxbxcxdxbbfxbx_1", -1 },
  { "API_47_PATCH_user_setting_me_code_generator_1", -1 },
  { "API_48_GET_dynamic_form_column_a_1", -1 },
  { "API_49_GET_role_role_x_1", -1 },
  { "API_50_POST_role_1", -1 },
  { "API_51_GET_dashboard_user_1", -1 },
  { "API_51_GET_dashboard_user_2", -1 },
  { "API_52_GET_person_1", -1 },
  { "API_52_GET_person_2", -1 },
  { "API_53_GET_role_role_x_1", -1 },
  { "API_54_GET_datasource_config_1", -1 },
  { "API_54_GET_datasource_config_2", -1 },
  { "API_54_GET_datasource_config_3", -1 },
  { "API_55_GET_permission_1", -1 },
  { "API_55_GET_permission_2", -1 },
  { "API_55_GET_permission_3", -1 },
  { "API_55_GET_permission_4", -1 },
  { "API_55_GET_permission_5", -1 },
  { "API_56_PATCH_autz_setting_1", -1 },
  { "API_56_PATCH_autz_setting_2", -1 },
  { "API_57_GET_role_dd_1", -1 },
  { "API_58_GET_menu_dxbxaxaxdxaxfxbbbacabxee_1", -1 },
  { "API_59_GET_datasource_config_x_1", -1 },
  { "API_60_GET_autz_setting_detail_organizational_1", -1 },
  { "API_61_GET_autz_setting_user_xccxeeecxdfxexbxexbx_1", -1 },
  { "API_62_GET_user_setting_me_code_generator_all_1", -1 },
  { "API_63_GET_autz_setting_role_role_x_1", -1 },
  { "API_64_GET_autz_setting_role_role_x_1", -1 },
  { "API_64_GET_autz_setting_role_role_x_2", -1 },
  { "API_65_PUT_dashboard_xbcxexcbbxcxbaxexex_1", -1 },
  { "API_66_PATCH_menu__1", -1 },
  { "API_66_PATCH_menu__2", -1 },
  { "API_67_PUT_role_role_x_1", -1 },
  { "API_68_PATCH_dashboard_1", -1 },
  { "API_68_PATCH_dashboard_2", -1 },
  { "API_69_GET_dashboard_1", -1 },
  { "API_69_GET_dashboard_2", -1 },
  { "API_70_GET_autz_setting_user_xedxexfafxexbaebexedbdad_1", -1 },
  { "API_71_PUT_role_role_x_1", -1 },
  { "API_72_DELETE_schedule_job_excxcxfxfxfxaxex_1", -1 },
  { "API_73_PATCH_dictionary_1", -1 },
  { "API_73_PATCH_dictionary_2", -1 },
  { "API_74_GET_dynamic_form_a_1", -1 },
  { "API_75_POST_workflow_model_x_deploy_1", -1 },
  { "API_76_GET_schedule_job_1", -1 },
  { "API_77_GET_database_manager_metas_x_1", -1 },
  { "API_78_GET_dynamic_form_1", -1 },
  { "API_78_GET_dynamic_form_2", -1 },
  { "API_79_GET_dashboard_xbcxexcbbxcxbaxexex_1", -1 },
  { "API_80_GET_permission_no_paging_1", -1 },
  { "API_80_GET_permission_no_paging_2", -1 },
  { "API_80_GET_permission_no_paging_3", -1 },
  { "API_81_GET_user_setting_me_code_gen_setsimple_gen_latest_1", -1 },
  { "API_82_POST_user_1", -1 },
  { "API_82_POST_user_2", -1 },
  { "API_83_GET_workflow_model_x_json_1", -1 },
}

