require("rand")
require("schema")

-- cache global to local
local _gen_default_value_f = _gen_default_value
local _gen_default_parameter_f = _gen_default_parameter
local _tables_t = tables

function get_table_size(_table_name)
    return _default_tables_size[_table_name]
end

function gen_value(_table_name, _col_name, _col_desc, _line_num)
    return _gen_default_value_f(_table_name, _col_name, _col_desc, _line_num)
end

function gen_parameter(_param_desc)
    local _api = _param_desc[1]
    local _sql = _param_desc[2]
    local _table = _param_desc[3]
    local _column = _param_desc[4]
    local _position = _param_desc[5]
    local _guessed_data_type = _param_desc[6]

    local _column_desc
    if _table ~= "" then
        _column_desc = _tables_t[_table][_column]
    end

    return _gen_default_parameter_f(_table, _column, _column_desc, _position, _guessed_data_type)
end
_default_tables_size = {
  ["customer_option_set"] = 10000,
  ["country"] = 10000,
  ["sm_transaction"] = 10000,
  ["userconnection"] = 10000,
  ["system_notification"] = 10000,
  ["merchant_store"] = 10000,
  ["product_attribute"] = 10000,
  ["product_image"] = 10000,
  ["language"] = 10000,
  ["product_price"] = 10000,
  ["tax_rate_description"] = 10000,
  ["tax_rate"] = 10000,
  ["customer_attribute"] = 10000,
  ["zone"] = 10000,
  ["manufacturer_description"] = 10000,
  ["product_option_value_description"] = 10000,
  ["product_description"] = 10000,
  ["shopping_cart"] = 10000,
  ["sm_sequencer"] = 10000,
  ["user_group"] = 10000,
  ["order_status_history"] = 10000,
  ["product_review"] = 10000,
  ["shopping_cart_attr_item"] = 10000,
  ["product_digital"] = 10000,
  ["product_image_description"] = 10000,
  ["permission_group"] = 10000,
  ["order_account"] = 10000,
  ["geozone"] = 10000,
  ["customer_optin"] = 10000,
  ["content_description"] = 10000,
  ["order_product"] = 10000,
  ["zone_description"] = 10000,
  ["file_history"] = 10000,
  ["geozone_description"] = 10000,
  ["customer_group"] = 10000,
  ["customer_option_desc"] = 10000,
  ["orders"] = 10000,
  ["order_total"] = 10000,
  ["shipping_quote"] = 10000,
  ["merchant_configuration"] = 10000,
  ["product_option_value"] = 10000,
  ["merchant_language"] = 10000,
  ["optin"] = 10000,
  ["merchant_log"] = 10000,
  ["product_option"] = 10000,
  ["content"] = 10000,
  ["manufacturer"] = 10000,
  ["category_description"] = 10000,
  ["system_configuration"] = 10000,
  ["customer_option_value"] = 10000,
  ["product_availability"] = 10000,
  ["product_relationship"] = 10000,
  ["currency"] = 10000,
  ["customer_review"] = 10000,
  ["product_option_desc"] = 10000,
  ["product_review_description"] = 10000,
  ["module_configuration"] = 10000,
  ["order_attribute"] = 10000,
  ["product"] = 10000,
  ["tax_class"] = 10000,
  ["shiping_origin"] = 10000,
  ["country_description"] = 10000,
  ["permission"] = 10000,
  ["shopping_cart_item"] = 10000,
  ["order_product_attribute"] = 10000,
  ["customer_opt_val_description"] = 10000,
  ["sm_group"] = 10000,
  ["product_type"] = 10000,
  ["product_price_description"] = 10000,
  ["customer_option"] = 10000,
  ["order_product_download"] = 10000,
  ["order_account_product"] = 10000,
  ["order_product_price"] = 10000,
  ["category"] = 10000,
  ["customer_review_description"] = 10000,
  ["user"] = 10000,
  ["product_category"] = 10000,
  ["customer"] = 10000,
}

_traces_dist = {
  { "API_1__admin_options_paging_html_1", -1 },
  { "API_2__admin_products_images_url_list_html_1", -1 },
  { "API_3__admin_products_images_page_html_1", -1 },
  { "API_4__services_public_search_DEFAULT_en_autocomplete_json_1", -1 },
  { "API_5__admin_user_groups_html_1", -1 },
  { "API_6__admin_store_removeImage_html_1", -1 },
  { "API_7__admin_reference_provinces_html_1", -1 },
  { "API_7__admin_reference_provinces_html_2", -1 },
  { "API_7__admin_reference_provinces_html_3", -1 },
  { "API_7__admin_reference_provinces_html_4", -1 },
  { "API_8__admin_shipping_shippingMethod_html_1", -1 },
  { "API_9__admin_product_categories_paging_html_1", -1 },
  { "API_10__shop_category_fffccccadfad_html_ref_c_x_1", -1 },
  { "API_11__shop_cart_shoppingCart_html_1", -1 },
  { "API_12__shop_category_basebakk_shoes_html_ref_c_x_1", -1 },
  { "API_13__admin_customers_optionsset_list_html_1", -1 },
  { "API_14__admin_shipping_saveShippingPackaging_html_1", -1 },
  { "API_15__admin_products_images_url_page_html_1", -1 },
  { "API_16__shop_category_basebakk_shoes_html_ref_c_x_x_1", -1 },
  { "API_17__shop_order_payment_init_PAYPAL_html_1", -1 },
  { "API_18__admin_shipping_shippingPackaging_html_1", -1 },
  { "API_19__admin_tax_taxrates_list_html_1", -1 },
  { "API_20__admin_tax_taxconfiguration_save_html_1", -1 },
  { "API_21__admin_products_displayProductToCategories_html_1", -1 },
  { "API_22__admin_store_checkStoreCode_html_1", -1 },
  { "API_23__admin_customers_save_html_1", -1 },
  { "API_24__admin_catalogue_featured_paging_html_1", -1 },
  { "API_25__shop_cart_updateShoppingCartItem_html_1", -1 },
  { "API_26__admin_payments_paymentMethod_html_1", -1 },
  { "API_27__admin_products_reviews_html_1", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_1", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_2", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_3", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_4", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_5", -1 },
  { "API_28__services_public_products_page_x_x_DEFAULT_en_basebakk_shoes_6", -1 },
  { "API_29__admin_products_images_list_html_1", -1 },
  { "API_30__shop_cart_removeShoppingCartItem_html_1", -1 },
  { "API_31__admin_store_storeCreate_html_1", -1 },
  { "API_32__admin_optionsvalues_paging_html_1", -1 },
  { "API_33__admin_products_save_html_1", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_1", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_2", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_3", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_4", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_5", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_6", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_7", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_8", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_9", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_10", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_11", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_12", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_13", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_14", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_15", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_16", -1 },
  { "API_34__shop_cart_displayMiniCartByCode_17", -1 },
  { "API_35__admin_customers_options_paging_html_1", -1 },
  { "API_36__admin_configuration_saveEmailConfiguration_html_1", -1 },
  { "API_37__shop_cart_removeMiniShoppingCartItem_1", -1 },
  { "API_38__admin_products_paging_html_1", -1 },
  { "API_38__admin_products_paging_html_2", -1 },
  { "API_39__shop_product_kuzima_html_ref_c_x_1", -1 },
  { "API_40__admin_content_pages_save_html_1", -1 },
  { "API_41__admin_store_paging_html_1", -1 },
  { "API_42__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_filter_BRAND_filter_value_x_1", -1 },
  { "API_43__admin_configuration_system_html_1", -1 },
  { "API_44__admin_products_products_html_1", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_1", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_2", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_3", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_4", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_5", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_6", -1 },
  { "API_45__services_public_products_page_x_x_DEFAULT_en_fffccccadfad_7", -1 },
  { "API_46__admin_shipping_saveShippingConfiguration_html_1", -1 },
  { "API_47__shop_search_search_html_1", -1 },
  { "API_48__admin_tax_taxclass_save_html_1", -1 },
  { "API_49__admin_users_checkUserCode_html_1", -1 },
  { "API_50__admin_content_page_html_1", -1 },
  { "API_50__admin_content_page_html_2", -1 },
  { "API_51__shop_1", -1 },
  { "API_51__shop_2", -1 },
  { "API_52__admin_customers_optionsset_save_html_1", -1 },
  { "API_53__admin_configuration_email_html_1", -1 },
  { "API_54__admin_store_storeLanding_html_1", -1 },
  { "API_55__admin_store_saveBranding_html_1", -1 },
  { "API_56__shop_cart_addShoppingCartItem_1", -1 },
  { "API_56__shop_cart_addShoppingCartItem_2", -1 },
  { "API_56__shop_cart_addShoppingCartItem_3", -1 },
  { "API_57__admin_customers_setCredentials_html_1", -1 },
  { "API_58__admin_shipping_shippingMethods_html_1", -1 },
  { "API_58__admin_shipping_shippingMethods_html_2", -1 },
  { "API_59__admin_products_attributes_page_html_1", -1 },
  { "API_60__admin_configuration_saveConfiguration_html_1", -1 },
  { "API_61__admin_shipping_shippingOptions_html_1", -1 },
  { "API_62__admin_content_pages_create_html_1", -1 },
  { "API_63__api_vx_search_1", -1 },
  { "API_64__admin_shipping_origin_get_html_1", -1 },
  { "API_64__admin_shipping_origin_get_html_2", -1 },
  { "API_65__admin_products_product_keywords_paging_html_1", -1 },
  { "API_66__admin_shipping_origin_post_html_1", -1 },
  { "API_67__shop_category_fffccccadfad_html_ref_c_x_x_1", -1 },
  { "API_68__admin_customers_options_values_paging_html_1", -1 },
  { "API_69__admin_products_product_keywords_html_1", -1 },
  { "API_70__admin_products_addProductToCategories_html_1", -1 },
  { "API_71__admin_options_saveOptionValue_html_1", -1 },
  { "API_72__admin_categories_paging_html_1", -1 },
  { "API_73__admin_categories_createCategory_html_1", -1 },
  { "API_74__shop_order_shippingQuotes_json_1", -1 },
  { "API_74__shop_order_shippingQuotes_json_2", -1 },
  { "API_75__admin_tax_taxrates_save_html_1", -1 },
  { "API_76__admin_content_checkContentCode_html_1", -1 },
  { "API_77__admin_products_groups_paging_html_1", -1 },
  { "API_78__admin_customers_customer_html_1", -1 },
  { "API_79__admin_orders_paging_html_1", -1 },
  { "API_80__admin_customers_optionsset_paging_html_1", -1 },
  { "API_80__admin_customers_optionsset_paging_html_2", -1 },
  { "API_81__admin_logon_html_1", -1 },
  { "API_82__admin_products_reviews_paging_html_1", -1 },
  { "API_83__admin_categories_checkCategoryCode_html_1", -1 },
  { "API_84__admin_shipping_countries_update_html_1", -1 },
  { "API_85__admin_categories_save_html_1", -1 },
  { "API_86__admin_users_save_html_1", -1 },
  { "API_86__admin_users_save_html_2", -1 },
  { "API_87__admin_shipping_shippingConfigs_html_1", -1 },
  { "API_88__admin_groups_editGroup_html_1", -1 },
  { "API_89__admin_users_displayUser_html_1", -1 },
  { "API_90__admin_payments_paymentMethods_html_1", -1 },
  { "API_90__admin_payments_paymentMethods_html_2", -1 },
  { "API_91__admin_store_saveLanding_html_1", -1 },
  { "API_92__admin_store_store_html_1", -1 },
  { "API_92__admin_store_store_html_2", -1 },
  { "API_93__admin_catalogue_manufacturer_save_html_1", -1 },
  { "API_94__admin_customers_options_values_save_html_1", -1 },
  { "API_95__admin_customers_options_save_html_1", -1 },
  { "API_96__admin_products_editProduct_html_1", -1 },
  { "API_97__admin_configuration_saveSystemConfiguration_html_1", -1 },
  { "API_98__admin_catalogue_related_paging_html_1", -1 },
  { "API_99__admin_catalogue_manufacturer_paging_html_1", -1 },
  { "API_100__shop_reference_provinces_html_1", -1 },
  { "API_100__shop_reference_provinces_html_2", -1 },
  { "API_100__shop_reference_provinces_html_3", -1 },
  { "API_100__shop_reference_provinces_html_4", -1 },
  { "API_101__admin_content_boxes_save_html_1", -1 },
  { "API_102__shop_pages_dfdadsg_html_1", -1 },
  { "API_103__admin_products_prices_paging_html_1", -1 },
  { "API_104__admin_customers_page_html_1", -1 },
  { "API_104__admin_customers_page_html_2", -1 },
  { "API_105__admin_store_editStore_html_1", -1 },
  { "API_106__admin_configuration_accounts_html_1", -1 },
  { "API_107__shop_store_DEFAULT_contact_1", -1 },
  { "API_108__admin_tax_taxrates_page_html_1", -1 },
  { "API_108__admin_tax_taxrates_page_html_2", -1 },
  { "API_109__admin_products_groups_save_html_1", -1 },
  { "API_110__admin_products_digitalProduct_html_1", -1 },
  { "API_111__admin_groups_paging_html_1", -1 },
  { "API_112__admin_products_attributes_list_html_1", -1 },
  { "API_113__admin_shipping_saveShippingOptions_html_1", -1 },
  { "API_114__admin_products_createProduct_html_1", -1 },
  { "API_115__admin_categories_hierarchy_html_1", -1 },
  { "API_116__admin_shipping_countries_paging_html_1", -1 },
  { "API_116__admin_shipping_countries_paging_html_2", -1 },
  { "API_117__admin_store_save_html_1", -1 },
  { "API_117__admin_store_save_html_2", -1 },
  { "API_118__admin_tax_taxclass_paging_html_1", -1 },
  { "API_119__admin_catalogue_related_list_html_1", -1 },
  { "API_120__shop_store_contactus_html_1", -1 },
  { "API_121__admin_payments_savePaymentMethod_html_1", -1 },
  { "API_121__admin_payments_savePaymentMethod_html_2", -1 },
  { "API_122__shop_order_checkout_html_1", -1 },
  { "API_122__shop_order_checkout_html_2", -1 },
  { "API_122__shop_order_checkout_html_3", -1 },
  { "API_123__admin_shipping_saveShippingMethod_html_1", -1 },
  { "API_124__admin_tax_taxconfiguration_edit_html_1", -1 },
  { "API_125__admin_products_prices_html_1", -1 },
  { "API_126__admin_home_html_1", -1 },
  { "API_126__admin_home_html_2", -1 },
  { "API_127__admin_content_pages_details_html_1", -1 },
  { "API_128__admin_catalogue_featured_list_html_1", -1 },
  { "API_129__admin_manufacturer_checkCode_html_1", -1 },
}

